### ISSUE TITLE
Colors Plugin display issues with Fashionable.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce-colors#5]
Because Fashionable creates a margin-right rule between product tabs, if you change the background color, this causes a mess with the tabs:

(http://cld.wthms.co/nwJ4)

(http://cld.wthms.co/11JoS)

The plugin also appears to add a blank content: css rule, which makes artifacts appear:

(http://cld.wthms.co/1khaI)

**Comment by claudiosmweb** [comment]
It is virtually impossible to prevent this type of problem =/
Because the plugin will try to override the theme CSS.
In case of problem perhaps it would be best not to use the plugin or manually correct the CSS.

I will remove the styles of tabs.
