### ISSUE TITLE
Custom CSS loaded on all pages, not just WooCommerce

### ISSUE THREAD

**Issue by mattradford** [woothemes/woocommerce-colors#6]
The header output code in includes/class-wc-colors-customizer.php outputs the custom CSS on all pages. If it's wrapped in a conditional then it'll only output on the required pages.

```
       if( is_woocommerce() || is_cart() || is_checkout() ) {
            echo "<!-- WooCommerce Colors -->\n";
            echo "<style type=\"text/css\">\n";
            echo $css;
            echo "\n</style>\n";
            echo "<!--/WooCommerce Colors-->\n";
        }
```

**Comment by claudiosmweb** [comment]
This styles is used for widgets and shortcodes.
So you need in more pages too.
